[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.tokenizer", "php82Extensions.bcmath", "php82Extensions.ctype", "php82Extensions.fileinfo", "php82Extensions.pdo_sqlite", "php82Extensions.sqlite3", "php82Extensions.curl", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.openssl", "nodejs_20", "php82Packages.composer"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "cp .env.example .env",
  "php artisan key:generate",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
